/* @oracle/oraclejet-preact: undefined */
import { jsx } from 'preact/jsx-runtime';
import './styles.styles.css';
export { a as SectionedContent, S as StickyPositioningDropdown } from './SectionedContent-815e377a.js';
import 'preact/hooks';
import './Dropdown-717319bb.js';
import './Floating-9703160e.js';
import 'preact/compat';
import './useFloating-c99976f8.js';
import './useUser-99920e02.js';
import './LayerHost-45f545d7.js';
import 'preact';
import './Common/themes/redwood/theme.js';
import './Common/themes/themeContract.css.js';
import './positionUtils-1ec41fd0.js';
import './refUtils-b9d8d91a.js';
import './useOutsideClick-eb8324f6.js';
import './arrayUtils-35a58161.js';
import './Layer-9b06412e.js';
import './classNames-4e12b00d.js';
import './UNSAFE_Layer/themes/LayerStyles.css.js';
import './LayerStyles.styles.css';
import './useThemeInterpolations-9bddc683.js';
import './useColorScheme-e1b17324.js';
import './useScale-d64a1a28.js';
import './theme-63551f30.js';
import './Theme-e6dec6db.js';
import './mergeInterpolations-e2db2a66.js';
import './mergeDeepWithKey-08531060.js';
import './_curry3-0b4222d7.js';
import './_curry1-25297e59.js';
import './_curry2-34316bcf.js';
import './_isObject-1fab0f5b.js';
import './useComponentTheme-d2f9e47f.js';
import './logger-c92f309c.js';
import './utils-6eab3a64.js';
import './colorUtils-16eb823f.js';
import './UNSAFE_Floating/themes/redwood/FloatingTheme.js';
import './UNSAFE_Floating/themes/FloatingStyles.css.js';
import './FloatingStyles.styles.css';
import './UNSAFE_Floating/themes/redwood/FloatingBaseTheme.css.js';
import './UNSAFE_Floating/themes/redwood/FloatingBaseTheme.styles.css';
import './UNSAFE_Floating/themes/redwood/FloatingVariants.css.js';
import './vanilla-extract-recipes-createRuntimeFn.esm-2aaf8c98.js';
import './vanilla-extract-dynamic.esm-2955d60a.js';
import './UNSAFE_Floating/themes/FloatingContract.css.js';
import './keyboardUtils-4db21770.js';
import './clientHints-c76a913b.js';
import './tabbableUtils-dca964ca.js';
import './head-6f17c50c.js';
import './_arity-be492b9e.js';
import './_isArray-694cc52d.js';
import './_isString-675f1de9.js';
import './usePopupAnimation-4be04290.js';
import './useAnimationStatus-9ef65f0c.js';
import './useAnimation-fe9990dc.js';
import './popupAnimationUtils-d4c27cd1.js';
import './UNSAFE_Dropdown/themes/dropdownStyles.css.js';
import './dropdownStyles.styles.css';
import './useOutsideMousedown-7307de8b.js';
import './animationUtils-5f409a6c.js';
import './Flex-24628925.js';
import './useTestId-adde554c.js';
import './boxalignment-486c5ac9.js';
import './size-782ed57a.js';
import './boxalignment.styles.css';
import './vanilla-extract-sprinkles-createRuntimeSprinkles.esm-2d655d37.js';
import './dimensions-5229d942.js';
import './flexbox-529f25da.js';
import './flexbox.styles.css';
import './flexitem-7b7f7920.js';
import './flexitem.styles.css';
import './FlexStyles.styles.css';
import './FocusTrap-8ddd383f.js';
import './FocusTracker-a0621449.js';
import './PRIVATE_FocusTracker/themes/FocusTrackerStyles.css.js';
import './FocusTrackerStyles.styles.css';
import './View-6013acac.js';
import './borders-98a63040.js';
import './colors-aab9ed12.js';
import './padding-01bef196.js';
import './aria-efa0582c.js';
import './EnvironmentProvider-f543a463.js';
import './LayerManager-625d2503.js';
import './useDensity-60cfa748.js';
import './equals-160da165.js';

var container = 'styles_container__sc292h0';
var wrapper = 'styles_wrapper__sc292h1';

const DemoContainer = (props) => (jsx("div", { ...props, className: container }));
const DemoWrapper = (props) => (jsx("div", { ...props, className: wrapper }));

export { DemoContainer, DemoWrapper };
//# sourceMappingURL=PRIVATE_FormControls.js.map
